version: '3.8'

services:
  userservice:
    build:
      context: .
      dockerfile: UserService/UserService.API/Dockerfile
    container_name: userservice
    ports:
      - "5224:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__UserDb=Host=userservice_db;Port=5432;Database=user;Username=postgres;Password=9485
      - JwtSettings__SecretKey=${JWT_SECRET_KEY:-QTzao1eY1adD9BMBGLzHv04KLZ98HapN70uINm1THcU=}
      - JwtSettings__Issuer=${JWT_ISSUER:-FreelanceGIGPlatform.API}
      - JwtSettings__Audience=${JWT_AUDIENCE:-FreelanceGIGPlatform.Client}
      - JwtSettings__ExpiryHours=${JWT_EXPIRY_HOURS:-1}
    depends_on:
      userservice_db:
        condition: service_healthy
    networks:
      - freelance-network
    restart: unless-stopped

  userservice_db:
    image: postgres:16-alpine
    container_name: userservice_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9485
      - POSTGRES_DB=user
    ports:
      - "5432:5432"
    volumes:
      - userservice_data:/var/lib/postgresql/data
    networks:
      - freelance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  jobservice:
    build:
      context: .
      dockerfile: JobService/JobService.API/Dockerfile
    container_name: jobservice
    ports:
      - "5225:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=jobservice_db;Port=5432;Database=job;Username=postgres;Password=9485
      - JwtSettings__SecretKey=${JWT_SECRET_KEY:-QTzao1eY1adD9BMBGLzHv04KLZ98HapN70uINm1THcU=}
      - JwtSettings__Issuer=${JWT_ISSUER:-FreelanceGIGPlatform.API}
      - JwtSettings__Audience=${JWT_AUDIENCE:-FreelanceGIGPlatform.Client}
      - JwtSettings__ExpiryHours=${JWT_EXPIRY_HOURS:-1}
    depends_on:
      jobservice_db:
        condition: service_healthy
    networks:
      - freelance-network
    restart: unless-stopped

  jobservice_db:
    image: postgres:16-alpine
    container_name: jobservice_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9485
      - POSTGRES_DB=job
    ports:
      - "5433:5432"
    volumes:
      - jobservice_data:/var/lib/postgresql/data
    networks:
      - freelance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d job"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  userservice_data:
  jobservice_data:

networks:
  freelance-network:
    driver: bridge

